### ISSUE TITLE
Change/Overwrite keyboard dimension

### ISSUE THREAD

**Issue by Alex66955** [protacon/ng-virtual-keyboard#10]
Is there a way to overwrite the default css layout configuration?
I have to run the keyboard on a 480x272 display and the default dimension is not able to display the keyboard correctly.

I identified following line as issue. If the 64 would be available from outside it would be nice. As alternative if it is defined as css style and it can be replaced from outside:
https://github.com/schenckprocesseurope/ng-virtual-keyboard/blob/master/src/virtual-keyboard-key.component.ts#L97

![image](https://user-images.githubusercontent.com/3258379/28916136-790d0f18-7841-11e7-8725-da2f8a8110ed.png)

**Comment by sancelot** [comment]
have you tried the phone layout?

**Comment by Alex66955** [comment]
> have you tried the phone layout?
It makes no difference. The layout is still not usable.

**Comment by SelfishLucho** [comment]
Hi, Not sure if u already solved this but if u look closer to the code it's built on top of Angular Material so if i understood your question right if u want to resize the popup dialog from where keyboard appears u simply can override the properties of the mddialog simply by using it's API [https://material.angular.io/components/dialog/overview](url)

**Comment by Alex66955** [comment]
> Hi, Not sure if u already solved this but if u look closer to the code it's built on top of Angular Material so if i understood your question right if u want to resize the popup dialog from where keyboard appears u simply can override the properties of the mddialog simply by using it's API https://material.angular.io/components/dialog/overview

I tried a few parameter but the layout is still not correct on a small device.
I found following code wich
