### ISSUE TITLE
@angular/material

### ISSUE THREAD

**Issue by Tefofo** [protacon/ng-virtual-keyboard#19]
Hi there,
the use of 'Md' in angular material has been deprecated, as a result, I am getting this trying to use the module:- 
ERROR in node_modules/@protacon/ng-virtual-keyboard/dist/virtual-keyboard.directive.d.ts(2,10): error TS2305: Module '".../node_modules/@protacon/ng-virtual-keyboard/node_modules/@angular/material/material"' has no exported member 'MdDialog'.

**Comment by tarlepp** [comment]
Solved with latest release 0.7.0
